# Generated by Django 5.2.15 on 2026-06-27 21:49

import shared.utils.encryption
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_role_level_historicalsector_sector_role_sector'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicaltenant',
            name='dpo_email',
            field=shared.utils.encryption.EncryptedEmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='historicaltenant',
            name='dpo_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='tenant',
            name='dpo_email',
            field=shared.utils.encryption.EncryptedEmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='tenant',
            name='dpo_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='userpreferences',
            name='language',
            field=models.CharField(default='pt-br', max_length=10),
        ),
        migrations.AddField(
            model_name='userpreferences',
            name='privacy_consent_accepted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userpreferences',
            name='privacy_consent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userpreferences',
            name='privacy_consent_ip',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
    ]
