# Generated by Django 5.2.15 on 2026-06-05 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalitem',
            name='minimum_stock',
            field=models.DecimalField(decimal_places=3, default=0.0, max_digits=12, verbose_name='Estoque Mínimo'),
        ),
        migrations.AddField(
            model_name='item',
            name='minimum_stock',
            field=models.DecimalField(decimal_places=3, default=0.0, max_digits=12, verbose_name='Estoque Mínimo'),
        ),
    ]
