# Generated by Django 5.2.15 on 2026-06-16 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0002_historicalitem_minimum_stock_item_minimum_stock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batch',
            name='status',
            field=models.CharField(choices=[('active', 'Ativo'), ('expired', 'Expirado'), ('discarded', 'Descartado'), ('depleted', 'Esgotado')], default='active', max_length=20, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='historicalbatch',
            name='status',
            field=models.CharField(choices=[('active', 'Ativo'), ('expired', 'Expirado'), ('discarded', 'Descartado'), ('depleted', 'Esgotado')], default='active', max_length=20, verbose_name='Status'),
        ),
    ]
