# Generated by Django 5.2.15 on 2026-06-26 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0003_alter_batch_status_alter_historicalbatch_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalitem',
            name='ncm',
            field=models.CharField(blank=True, db_index=True, max_length=10, null=True, verbose_name='NCM'),
        ),
        migrations.AlterField(
            model_name='item',
            name='ncm',
            field=models.CharField(blank=True, db_index=True, max_length=10, null=True, verbose_name='NCM'),
        ),
    ]
