# Generated by Django 5.2.15 on 2026-06-04 23:01

import uuid

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models

import apps.commercial.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalPartner',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('updated_at', models.DateTimeField(blank=True, editable=False)),
                ('is_customer', models.BooleanField(default=False, verbose_name='Cliente')),
                ('is_supplier', models.BooleanField(default=False, verbose_name='Fornecedor')),
                ('is_carrier', models.BooleanField(default=False, verbose_name='Transportadora')),
                ('person_type', models.CharField(choices=[('individual', 'Pessoa Física (PF)'), ('company', 'Pessoa Jurídica (PJ)')], default='company', max_length=20, verbose_name='Tipo de Pessoa')),
                ('legal_name', models.CharField(max_length=255, verbose_name='Razão Social / Nome Completo')),
                ('trade_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Nome Fantasia / Apelido')),
                ('document', models.CharField(max_length=20, validators=[apps.commercial.models.validate_document], verbose_name='CPF/CNPJ')),
                ('state_registration', models.CharField(blank=True, max_length=50, null=True, verbose_name='Inscrição Estadual')),
                ('municipal_registration', models.CharField(blank=True, max_length=50, null=True, verbose_name='Inscrição Municipal')),
                ('website', models.URLField(blank=True, null=True, verbose_name='Site')),
                ('integration_code', models.CharField(blank=True, max_length=100, null=True, verbose_name='Código de Integração')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('created_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.tenant')),
                ('updated_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical parceiro',
                'verbose_name_plural': 'historical parceiros',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_customer', models.BooleanField(default=False, verbose_name='Cliente')),
                ('is_supplier', models.BooleanField(default=False, verbose_name='Fornecedor')),
                ('is_carrier', models.BooleanField(default=False, verbose_name='Transportadora')),
                ('person_type', models.CharField(choices=[('individual', 'Pessoa Física (PF)'), ('company', 'Pessoa Jurídica (PJ)')], default='company', max_length=20, verbose_name='Tipo de Pessoa')),
                ('legal_name', models.CharField(max_length=255, verbose_name='Razão Social / Nome Completo')),
                ('trade_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Nome Fantasia / Apelido')),
                ('document', models.CharField(max_length=20, validators=[apps.commercial.models.validate_document], verbose_name='CPF/CNPJ')),
                ('state_registration', models.CharField(blank=True, max_length=50, null=True, verbose_name='Inscrição Estadual')),
                ('municipal_registration', models.CharField(blank=True, max_length=50, null=True, verbose_name='Inscrição Municipal')),
                ('website', models.URLField(blank=True, null=True, verbose_name='Site')),
                ('integration_code', models.CharField(blank=True, max_length=100, null=True, verbose_name='Código de Integração')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partners', to='core.tenant')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'parceiro',
                'verbose_name_plural': 'parceiros',
                'unique_together': {('tenant', 'document')},
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nome')),
                ('email', models.EmailField(max_length=254, verbose_name='E-mail')),
                ('phone', models.CharField(max_length=20, verbose_name='Telefone')),
                ('role', models.CharField(blank=True, max_length=100, null=True, verbose_name='Cargo')),
                ('is_primary', models.BooleanField(default=False, verbose_name='Contato Principal')),
                ('partner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='commercial.partner')),
            ],
            options={
                'verbose_name': 'contato',
                'verbose_name_plural': 'contatos',
            },
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=100, verbose_name='Rótulo (ex: Matriz, Filial)')),
                ('zip_code', models.CharField(max_length=10, verbose_name='CEP')),
                ('street', models.CharField(max_length=255, verbose_name='Logradouro')),
                ('number', models.CharField(max_length=20, verbose_name='Número')),
                ('complement', models.CharField(blank=True, max_length=100, null=True, verbose_name='Complemento')),
                ('neighborhood', models.CharField(max_length=100, verbose_name='Bairro')),
                ('city', models.CharField(max_length=100, verbose_name='Cidade')),
                ('state', models.CharField(max_length=2, verbose_name='UF')),
                ('country', models.CharField(default='BR', max_length=100, verbose_name='País')),
                ('is_collection', models.BooleanField(default=False, verbose_name='Endereço de Coleta')),
                ('is_delivery', models.BooleanField(default=False, verbose_name='Endereço de Entrega')),
                ('partner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to='commercial.partner')),
            ],
            options={
                'verbose_name': 'endereço',
                'verbose_name_plural': 'endereços',
            },
        ),
    ]
